server:
 port: 8077
 servlet:
  context-path: /acoustic-search
 tomcat:    threads:      max: 10
  
---

spring:
 datasource:
  url: jdbc:h2:mem:testdb
  driver-class-name: org.h2.Driver
  username: admin
  password: admin
 jpa:    show-sql: true    hibernate:      ddl-auto: update
 h2:    console:      enabled: true      path: /h2

---

logging:  level:    '[com.acoustic.search]': debug
    '[org.springframework.web]': debug
    '[org.springframework.boot,logging.level.web]': debug  file:    path: /app/acoustic-search/logs/acoustic-se.log
debug: false
